In [ ]:
import pandas as pd

In [ ]:
# Load dataset
df = pd.read_csv(r"c:\Users\DELL\Desktop\Product.csv")

In [ ]:
# Display number of rows and columns
df.shape

(800, 6)

In [ ]:
# Create data profiling report
data_profiling = pd.DataFrame ({
    "columns" : df.columns,
    "dtype" : df.dtypes.values,
    "unique_values" : df.nunique().values
})

data_profiling

    columns   dtype  unique_values
0      name  object            340
1       sku  object            800
2        id  object            800
3  isActive    bool              2
4  category  object              8
5  imageUrl  object              8

In [ ]:
# Create a report for missing values
missing_values = df.isnull().sum()

missing_percentage = (missing_values / len(df)) * 100
 
missing_report = pd.DataFrame ({
    "columns" : df.columns,
    "missing_values" : missing_values.values,
    "missing_percentage" : missing_percentage.values
})

missing_report

    columns  missing_values  missing_percentage
0      name               0                 0.0
1       sku               0                 0.0
2        id               0                 0.0
3  isActive               0                 0.0
4  category               0                 0.0
5  imageUrl               0                 0.0

In [ ]:
# Check for duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [ ]:
# Check for duplicate values in the "sku" column
df["sku"].duplicated().sum()

np.int64(0)

In [ ]:
# Generate unique skus by appending numbers to duplicate skus
count = df.groupby("sku").cumcount()

df["sku"] = df["sku"] + count.replace(0, "").astype(str)

In [ ]:
# Verify that all skus are now unique
df["sku"].duplicated().sum()

np.int64(0)

In [ ]:
# Save the cleaned dataset to a new CSV file
df.to_csv(r"c:\Users\DELL\Desktop\updated_product.csv", index = False)